Feature/pulumi aci support
cool-tech-dad/minecraft-vending-machine pull request #3
Opened 2022-01-22 07:18 UTC by bbabcock1990

Added Pulumi support for the MVM using ACI and Python.

2022-01-26 20:26 UTC, cool-tech-dad requested changes
Please fetch the last commit to main, and merge into your repo, address comments and re-commit.

2022-01-26 20:26 UTC, x0techdad commented on deploy-aci/pulumi/.gitignore
> +*.pyc
@bbabcock1990 feel free to add these entries into the repo-level .gitignore file.

2022-01-26 20:26 UTC, x0techdad commented on deploy-aci/pulumi/__main__.py
> +        image="docker.io/cooltechdad/minecraft-bds:0.5",
should be v0.6 of the image now. please change and test deployment to make sure were good. thanks!

2022-01-26 20:33 UTC, bbabcock1990 commented on deploy-aci/pulumi/.gitignore
> +*.pyc
Sounds Good

2022-01-26 20:34 UTC, bbabcock1990 commented on deploy-aci/pulumi/__main__.py
> +        image="docker.io/cooltechdad/minecraft-bds:0.5",
Instead of hard coding this as its subject to versioning, I will make this a variable.

2022-01-29 22:36 UTC, x0cooltechdad commented on deploy-aci/pulumi/__main__.py
> +        image="docker.io/cooltechdad/minecraft-bds:0.5",
added variable "docker_image_uri"

2022-01-29 22:44 UTC, x0cooltechdad approved these changes

2022-02-04 20:19 UTC, x0cooltechdad approved these changes

2022-02-04 20:20 UTC, x0cooltechdad approved these changes

2022-02-04 20:25 UTC, merged